spring:
  application:
    name: microservice-spring-boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot?useTimezone=true&serverTimezone=UTC
    username: joselui3
    password: 840318Bd@
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # não necessita mais desta coonfiguração
    show-sql: false
logging:
  level:
    br.com.zeluiz_dev: INFO