server:
  port: 8080
spring:
  application:
    name: greeting-service
  config:
    import: optional:configserver:http://localhost:8888/
  # SETA PROFILE DEFAULT
  cloud:
    config:
      profile: dev
# ACTUATOR
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'  # ESPÕE TODOS OS ENDPOINT
  # ENDPOIT DETALHADO
  endpoint:
    health:
      show-details: ALWAYS
#greeting-service:
#  greeting: "Olá"
#  default-value: "Mundo!"
