server:
  port: 8888
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jose-luiz-18-bd/microservice_config_server
          #username: user_name
          #password: password
          default-label: main
          search-paths:
            - 'greeting-service*'
#  profiles:
#    active:
#      - native